### PR TITLE
Rejigger directories, drop cosign

### PR DESCRIPTION
**Pull request by vaikas**
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>

#### Summary
Move directories around, basically drop the extra cosign and cosign/kubernetes since it does not make
sense anymore.

#### Ticket Link

Fixes

#### Release Note

```release-note
For Downstream projects, the import paths for webhook parts have been changed:
"github.com/sigstore/policy-controller/pkg/cosign/kubernetes/webhook" => "github.com/sigstore/policy-controller/pkg/webhook"
ko://github.com/sigstore/policy-controller/cmd/cosign/policy_webhook =>  ko://github.com/sigstore/policy-controller/cmd/policy_webhook

```

### CODE REVIEW

**Review by cpanato — DISMISSED** [review]
thanks!

**Comment by cpanato** [comment]
@vaikas need to update here as well

https://github.com/sigstore/policy-controller/blob/main/config/webhook.yaml#L46 and https://github.com/sigstore/policy-controller/blob/main/config/webhook.yaml#L46

**Comment by vaikas** [comment]
Thought I did?
https://github.com/sigstore/policy-controller/pull/21/files#diff-c36bf41659a0c34415c335aa6c8002f4ebd63934551be3be811541128da9d425

https://github.com/sigstore/policy-controller/pull/21/files#diff-4213c7f740ecdc884863e3f1494d3f11240699de0d83025801e8e08fc25ad62b

But clearly I screwed something up.
Looking...

**Comment by vaikas** [comment]
ah, Makefile.

**Review by cpanato — APPROVED** [review]

**Pull request merged**
