### PR TITLE
Upgrade scaffolding to v0.7.2

### PR DESCRIPTION
**Pull request by malancas**
#### Summary

Upgrade scaffolding to `v0.7.2` in the Kind related workflows. This will resolve the metallb related errors we are seeing in the Kind testing workflows.

### CODE REVIEW

**Comment by malancas** [comment]
cc @hectorj2f @vaikas just wanted to give you guys a heads up

**Comment by vaikas** [comment]
Looks like 7.2 was cut? Can we try with that?

**Comment by vaikas** [comment]
Looks like both tests failed with expired TUF root 🤔 

```
--- FAIL: TestClientFromSerializedMirror (0.00s)
    repo_test.go:206: Failed to unserialize repo: failed to update TUF client: tuf: failed to decode root.json: expired at 2024-06-14 18:52:45 +0000 UTC

```

**Comment by malancas** [comment]
> Looks like 7.2 was cut? Can we try with that?

Perfect timing, just updated to 7.2

**Comment by vaikas** [comment]
Looks like it failed again, haha, looks like the testdata needs to be recreated:
https://github.com/sigstore/policy-controller/blob/f099546d3ce22170217ac170191c3b7e97371ab9/pkg/tuf/repo_test.go#L73

**Comment by malancas** [comment]
Throwing this back into draft while I work on the other test failures.

**Comment by hectorj2f** [comment]
@malancas Do you know how to fix the tuf expiration ? Otherwise I can take some time tomorrow morning to fix it.

**Comment by malancas** [comment]
> @malancas Do you know how to fix the tuf expiration ? Otherwise I can take some time tomorrow morning to fix it.

I don't think so. I'll remove the initial TUF changes from this PR and just let this update the scaffolding version if you have time to work on the TUF expiration.

**Comment by hectorj2f** [comment]
@malancas You could cherry pick my changes from here https://github.com/sigstore/policy-controller/pull/1496 if you prefer.

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
thanks @malancas for the fix! i did a rebase to unblock ci and we were able to merge the other PRs in the queue, hope you dont mind

**Review by hectorj2f — APPROVED** [review]

**Pull request merged**
