### PR TITLE
Add TUF support to the policy-tester tool

### PR DESCRIPTION
**Pull request by malancas**
#### Summary

This adds TUF support to the policy-tester tool. The TUF handling code used by the tool is already unit tested. This just updates the policy-tester to check whether the provided `TrustRoot` custom resource specifies one of the "bring your own keys", remote, or repository fields.

### CODE REVIEW

**Review by hectorj2f — DISMISSED** [review]

**Review by codysoyland — APPROVED** [review]
This is great, thanks @malancas!

**Review by hectorj2f — APPROVED** [review]
lgtm

**Comment by malancas** [comment]
@hectorj2f thanks for reviewing. There is one [failing check](https://github.com/sigstore/policy-controller/actions/runs/8989108714/job/24691456701?pr=1407) that seems like it's unrelated. Would you be able to rerun it?

**Comment by hectorj2f** [comment]
Yes, done!.

**Comment by malancas** [comment]
@hectorj2f would you mind merging this PR? I don't have write access so I can't merge it.

**Pull request merged**
