### PR TITLE
Use TUF instead of env variables.

### PR DESCRIPTION
**Pull request by vaikas**
#### Summary
Add two new flags that you can use to specify how to initialize TUF root.
--tuf-mirror
--tuf-root

We then do equivalent of cosign initialize with those.

#### Release Note
* Add two new flags that allow you to bring in a custom TUF root: --tuf-mirror and --tuf-root.
* DEPRECATED: Enviromental variables should be considered deprecated as the whole sigstore is moving everything to TUF.

### CODE REVIEW

**Comment by vaikas** [comment]
If all works here, I'd like to use this instead of #157 so that we don't need to bring in the additional initContainer.

**Review by cpanato — APPROVED** [review]

**Review by hectorj2f — DISMISSED** [review]
lgtm

**Comment by vaikas** [comment]
Thanks so much @cpanato for making kustomize work, super neat!

**Review by hectorj2f — APPROVED** [review]

**Comment by vaikas** [comment]
Documentation changes here:
https://github.com/sigstore/sigstore-website/pull/214

**Pull request merged**
