### PR TITLE
drop 1.27/28 and add 1.30/31/32 k8s

### PR DESCRIPTION
**Pull request by cpanato**

### CODE REVIEW

**Comment by cpanato** [comment]
if approved we need to update the GH checks, i will do that

**Review by vaikas — DISMISSED** [review]
Thanks @cpanato !!

**Comment by hectorj2f** [comment]
Thanks

**Comment by vaikas** [comment]
Tuf root expired 🤣 
```
--- FAIL: TestClientFromSerializedMirror (0.00s)
    repo_test.go:206: Failed to unserialize repo: failed to update TUF client: tuf: failed to decode root.json: expired at 2024-12-18 18:47:22 +0000 UTC

```

**Comment by hectorj2f** [comment]
Tuf root expired like on every 🎄🎁.

**Comment by cpanato** [comment]
update checks https://github.com/sigstore/community/pull/525

**Review by hectorj2f — APPROVED** [review]

**Comment by cpanato** [comment]
> @cpanato we need to change the Ci checks is expecting k8s 1.28 and 1.27.

yes, pr is here https://github.com/sigstore/community/pull/525

**Review by hectorj2f — APPROVED** [review]

**Pull request merged**
