### PR TITLE
Add api docs generator

### PR DESCRIPTION
**Pull request by hectorj2f**
Signed-off-by: Hector Fernandez <hector@chainguard.dev>

#### Summary

We are currently missing any documentation related to the api docs and the purpose of each field.

#### Release Note

Auto-generate API documentation for each ClusterImagePolicy field.

### CODE REVIEW

**Review by vaikas — APPROVED** [review]
Woot Woot!!! Thank you!!!

**Comment by vaikas** [comment]
I think the tests are flaking because the batch job is not there yet?
```
  service/default-domain-service created
  Error from server (NotFound): jobs.batch "default-domain" not found
  Error: Process completed with exit code 1.
```

I think that should've been fixed here:
https://github.com/sigstore/scaffolding/pull/374

**Review by cpanato — APPROVED** [review]
<3

**Comment by hectorj2f** [comment]
Thanks @cpanato

**Pull request merged**
