### PR TITLE
cleanup: switch to using cosign v2.0.0-rc.0

### PR DESCRIPTION
**Pull request by k4leung4**
Signed-off-by: Kenny Leung <kleung@chainguard.dev>

#### Summary

switch to using cosign v2.0.0-rc.0

update use of `--force` to `--yes` for cosign sign|attest, https://github.com/sigstore/cosign/pull/2399
update use of `--no-tlog-upload` to `--tlog-upload=false`, https://github.com/sigstore/cosign/pull/2397

### CODE REVIEW

**Comment by k4leung4** [comment]
@hectorj2f @vaikas Any idea why this might be failing with cosign v2-rc0?

https://github.com/sigstore/policy-controller/actions/runs/3833129528/jobs/6524241482

**Comment by vaikas** [comment]
I think this might be related to https://github.com/sigstore/policy-controller/issues/479

```
Create one keyless attestation and verify it, but no tlog upload
  + echo '::group:: Create one keyless attestation and verify it, but no tlog upload'
```

**Comment by vaikas** [comment]
I think it's actually failing because the cosign is failing the verify-attestation from the looks of it and not the policy-controller, I put together #486 as a test for that.

**Comment by vaikas** [comment]
Yeah, so here:
https://github.com/sigstore/cosign/pull/2505

**Review by vaikas — APPROVED** [review]

**Pull request merged**
