### PR TITLE
upgrade Go to 1.21

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- upgrade Go to 1.21

### CODE REVIEW

**Comment by bobcallaway** [comment]
should we use https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file to avoid having to change a bunch of these files in the future?

**Comment by cpanato** [comment]
> should we use https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file to avoid having to change a bunch of these files in the future?

not strong opinion here, will make the change to use that

**Comment by cpanato** [comment]
ping @vaikas @bobcallaway

**Review by bobcallaway — DISMISSED** [review]

**Review by hectorj2f — APPROVED** [review]
LGTM

**Review by hectorj2f — APPROVED** [review]
Thanks

**Pull request merged**
