### PR TITLE
Update to cosign HEAD, add replace for glog

### PR DESCRIPTION
**Pull request by jdolitsky**
Discovered this issue in #103 - the latest cosign pulls in `github.com/golang/glog` which causes the known `-log_dir` error:

```
2022-07-25T18:17:08.332612658Z stderr F /ko-app/policy_webhook flag redefined: log_dir
2022-07-25T18:17:08.334789372Z stderr F panic: /ko-app/policy_webhook flag redefined: log_dir
```

After updating to cosign HEAD, the tests detect this coming in via `github.com/google/certificate-transparency-go`:
```
    --- FAIL: TestNoDeps/github.com/sigstore/policy-controller/cmd/webhook (1.72s)
        depcheck.go:126: CheckNoDependency() = github.com/sigstore/policy-controller/cmd/webhook depends on banned dependency github.com/golang/glog
            github.com/sigstore/policy-controller/cmd/webhook
            github.com/sigstore/policy-controller/pkg/webhook
            github.com/sigstore/cosign/pkg/policy
            github.com/sigstore/cosign/cmd/cosign/cli/options  # Also: [github.com/sigstore/cosign/pkg/cosign/git github.com/sigstore/cosign/pkg/cosign/git/github github.com/sigstore/cosign/pkg/cosign/git/gitlab github.com/sigstore/cosign/pkg/cosign/kubernetes github.com/sigstore/cosign/pkg/signature github.com/sigstore/policy-controller/pkg/webhook]
            github.com/sigstore/cosign/pkg/cosign
            github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioverifier/ctl
            github.com/google/certificate-transparency-go/x509util
            github.com/golang/glog
```

So I've create a [fork](https://github.com/jdolitsky/glog/tree/remove-log-dir) of glog which simply [renames](https://github.com/jdolitsky/glog/commit/b10376801ddeee929e3032bc2fa280a0b6600a37) that flag to `-glog_dir`.

I'm not a fan of having a personal fork replace statement, but I'm not sure the alternative here for upgrading. Perhaps we can have a fork under sigstore.

### CODE REVIEW

**Comment by jdolitsky** [comment]
Turns out there are more conflicting flags, so [I prefixed them all with "glog"](https://github.com/jdolitsky/glog/commit/78744e90d0874157648b0534f9b4e89892785fca)
```
2022-07-29T17:15:24.15275472Z stderr F /ko-app/policy_webhook flag redefined: logtostderr
2022-07-29T17:15:24.155101316Z stderr F panic: /ko-app/policy_webhook flag redefined: logtostderr
```

**Comment by dlorenc** [comment]
My 2c - using the personal fork temporarily is fine to unblock progress, just open an issue to track removal with any ideas we have to fix this long term.

**Comment by jdolitsky** [comment]
> open an issue to track removal with any ideas we have to fix this long term

Opened https://github.com/sigstore/cosign/issues/2113

**Comment by jdolitsky** [comment]
Another option here is to maintain the forked glog in a `glog/` directory (or maybe `internal/glog`), since the whole package is just 3 files. I'm just not sure how that should be handled in terms of licensing etc.

**Review by vaikas — APPROVED** [review]
Thank you so much for tracking this down. I'm totes fine for merging this to make progress. Once we understand the fate of the other upstream changes, we can figure out if fork makes sense.

**Comment by mattmoor** [comment]
Thanks for chasing this down, Josh! 🤩 

Hopefully we can sort out a more permanent solution for this one way or another soon 🤞

**Review by hectorj2f — APPROVED** [review]

**Comment by jdolitsky** [comment]
🙌

**Pull request merged**
